### ISSUE TITLE
Ship moves offscreen left and right

### ISSUE THREAD

**Issue by creikey** [vikinggames/ArcadeExample#3]
Add a constrain thing that makes it so the ship doesn't go offscreen

**Comment by 306760** [comment]
I can do this

**Comment by creikey** [comment]
@306760 I have assigned you the issue. It's pretty urgent, can you do this by tonight?

**Comment by 306760** [comment]
@creikey Yes

**Comment by creikey** [comment]
@306760 I'm going to finish this one off, as you can't actually run Godot

**Comment by creikey** [comment]
Finished it in most recent pull request
